spring.application.name=LoanManagement

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/loan_db
spring.datasource.username=postgres
spring.datasource.password=1010
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


loan.service.mock=true


od.interest.rate=12.0
od.limit.percentage=20
od.tenure.months=12
prepayment.charge.percent=2.0
min.part.payment=5000