/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.educationloan.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DocumentUploadedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3268469973818146456L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DocumentUploadedEvent\",\"namespace\":\"com.educationloan.avro\",\"fields\":[{\"name\":\"documentId\",\"type\":\"string\"},{\"name\":\"applicantId\",\"type\":\"long\"},{\"name\":\"loanId\",\"type\":\"long\"},{\"name\":\"documentType\",\"type\":\"string\"},{\"name\":\"filename\",\"type\":\"string\"},{\"name\":\"s3Key\",\"type\":\"string\"},{\"name\":\"contentType\",\"type\":\"string\"},{\"name\":\"fileSize\",\"type\":\"long\"},{\"name\":\"uploadedAt\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DocumentUploadedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DocumentUploadedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DocumentUploadedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DocumentUploadedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DocumentUploadedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DocumentUploadedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DocumentUploadedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DocumentUploadedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DocumentUploadedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence documentId;
  private long applicantId;
  private long loanId;
  private java.lang.CharSequence documentType;
  private java.lang.CharSequence filename;
  private java.lang.CharSequence s3Key;
  private java.lang.CharSequence contentType;
  private long fileSize;
  private java.lang.CharSequence uploadedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DocumentUploadedEvent() {}

  /**
   * All-args constructor.
   * @param documentId The new value for documentId
   * @param applicantId The new value for applicantId
   * @param loanId The new value for loanId
   * @param documentType The new value for documentType
   * @param filename The new value for filename
   * @param s3Key The new value for s3Key
   * @param contentType The new value for contentType
   * @param fileSize The new value for fileSize
   * @param uploadedAt The new value for uploadedAt
   */
  public DocumentUploadedEvent(java.lang.CharSequence documentId, java.lang.Long applicantId, java.lang.Long loanId, java.lang.CharSequence documentType, java.lang.CharSequence filename, java.lang.CharSequence s3Key, java.lang.CharSequence contentType, java.lang.Long fileSize, java.lang.CharSequence uploadedAt) {
    this.documentId = documentId;
    this.applicantId = applicantId;
    this.loanId = loanId;
    this.documentType = documentType;
    this.filename = filename;
    this.s3Key = s3Key;
    this.contentType = contentType;
    this.fileSize = fileSize;
    this.uploadedAt = uploadedAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return documentId;
    case 1: return applicantId;
    case 2: return loanId;
    case 3: return documentType;
    case 4: return filename;
    case 5: return s3Key;
    case 6: return contentType;
    case 7: return fileSize;
    case 8: return uploadedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: documentId = (java.lang.CharSequence)value$; break;
    case 1: applicantId = (java.lang.Long)value$; break;
    case 2: loanId = (java.lang.Long)value$; break;
    case 3: documentType = (java.lang.CharSequence)value$; break;
    case 4: filename = (java.lang.CharSequence)value$; break;
    case 5: s3Key = (java.lang.CharSequence)value$; break;
    case 6: contentType = (java.lang.CharSequence)value$; break;
    case 7: fileSize = (java.lang.Long)value$; break;
    case 8: uploadedAt = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'documentId' field.
   * @return The value of the 'documentId' field.
   */
  public java.lang.CharSequence getDocumentId() {
    return documentId;
  }


  /**
   * Sets the value of the 'documentId' field.
   * @param value the value to set.
   */
  public void setDocumentId(java.lang.CharSequence value) {
    this.documentId = value;
  }

  /**
   * Gets the value of the 'applicantId' field.
   * @return The value of the 'applicantId' field.
   */
  public long getApplicantId() {
    return applicantId;
  }


  /**
   * Sets the value of the 'applicantId' field.
   * @param value the value to set.
   */
  public void setApplicantId(long value) {
    this.applicantId = value;
  }

  /**
   * Gets the value of the 'loanId' field.
   * @return The value of the 'loanId' field.
   */
  public long getLoanId() {
    return loanId;
  }


  /**
   * Sets the value of the 'loanId' field.
   * @param value the value to set.
   */
  public void setLoanId(long value) {
    this.loanId = value;
  }

  /**
   * Gets the value of the 'documentType' field.
   * @return The value of the 'documentType' field.
   */
  public java.lang.CharSequence getDocumentType() {
    return documentType;
  }


  /**
   * Sets the value of the 'documentType' field.
   * @param value the value to set.
   */
  public void setDocumentType(java.lang.CharSequence value) {
    this.documentType = value;
  }

  /**
   * Gets the value of the 'filename' field.
   * @return The value of the 'filename' field.
   */
  public java.lang.CharSequence getFilename() {
    return filename;
  }


  /**
   * Sets the value of the 'filename' field.
   * @param value the value to set.
   */
  public void setFilename(java.lang.CharSequence value) {
    this.filename = value;
  }

  /**
   * Gets the value of the 's3Key' field.
   * @return The value of the 's3Key' field.
   */
  public java.lang.CharSequence getS3Key() {
    return s3Key;
  }


  /**
   * Sets the value of the 's3Key' field.
   * @param value the value to set.
   */
  public void setS3Key(java.lang.CharSequence value) {
    this.s3Key = value;
  }

  /**
   * Gets the value of the 'contentType' field.
   * @return The value of the 'contentType' field.
   */
  public java.lang.CharSequence getContentType() {
    return contentType;
  }


  /**
   * Sets the value of the 'contentType' field.
   * @param value the value to set.
   */
  public void setContentType(java.lang.CharSequence value) {
    this.contentType = value;
  }

  /**
   * Gets the value of the 'fileSize' field.
   * @return The value of the 'fileSize' field.
   */
  public long getFileSize() {
    return fileSize;
  }


  /**
   * Sets the value of the 'fileSize' field.
   * @param value the value to set.
   */
  public void setFileSize(long value) {
    this.fileSize = value;
  }

  /**
   * Gets the value of the 'uploadedAt' field.
   * @return The value of the 'uploadedAt' field.
   */
  public java.lang.CharSequence getUploadedAt() {
    return uploadedAt;
  }


  /**
   * Sets the value of the 'uploadedAt' field.
   * @param value the value to set.
   */
  public void setUploadedAt(java.lang.CharSequence value) {
    this.uploadedAt = value;
  }

  /**
   * Creates a new DocumentUploadedEvent RecordBuilder.
   * @return A new DocumentUploadedEvent RecordBuilder
   */
  public static com.educationloan.avro.DocumentUploadedEvent.Builder newBuilder() {
    return new com.educationloan.avro.DocumentUploadedEvent.Builder();
  }

  /**
   * Creates a new DocumentUploadedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DocumentUploadedEvent RecordBuilder
   */
  public static com.educationloan.avro.DocumentUploadedEvent.Builder newBuilder(com.educationloan.avro.DocumentUploadedEvent.Builder other) {
    if (other == null) {
      return new com.educationloan.avro.DocumentUploadedEvent.Builder();
    } else {
      return new com.educationloan.avro.DocumentUploadedEvent.Builder(other);
    }
  }

  /**
   * Creates a new DocumentUploadedEvent RecordBuilder by copying an existing DocumentUploadedEvent instance.
   * @param other The existing instance to copy.
   * @return A new DocumentUploadedEvent RecordBuilder
   */
  public static com.educationloan.avro.DocumentUploadedEvent.Builder newBuilder(com.educationloan.avro.DocumentUploadedEvent other) {
    if (other == null) {
      return new com.educationloan.avro.DocumentUploadedEvent.Builder();
    } else {
      return new com.educationloan.avro.DocumentUploadedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for DocumentUploadedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DocumentUploadedEvent>
    implements org.apache.avro.data.RecordBuilder<DocumentUploadedEvent> {

    private java.lang.CharSequence documentId;
    private long applicantId;
    private long loanId;
    private java.lang.CharSequence documentType;
    private java.lang.CharSequence filename;
    private java.lang.CharSequence s3Key;
    private java.lang.CharSequence contentType;
    private long fileSize;
    private java.lang.CharSequence uploadedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.educationloan.avro.DocumentUploadedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.documentId)) {
        this.documentId = data().deepCopy(fields()[0].schema(), other.documentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.applicantId)) {
        this.applicantId = data().deepCopy(fields()[1].schema(), other.applicantId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.loanId)) {
        this.loanId = data().deepCopy(fields()[2].schema(), other.loanId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.documentType)) {
        this.documentType = data().deepCopy(fields()[3].schema(), other.documentType);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.filename)) {
        this.filename = data().deepCopy(fields()[4].schema(), other.filename);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.s3Key)) {
        this.s3Key = data().deepCopy(fields()[5].schema(), other.s3Key);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.contentType)) {
        this.contentType = data().deepCopy(fields()[6].schema(), other.contentType);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.fileSize)) {
        this.fileSize = data().deepCopy(fields()[7].schema(), other.fileSize);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.uploadedAt)) {
        this.uploadedAt = data().deepCopy(fields()[8].schema(), other.uploadedAt);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing DocumentUploadedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.educationloan.avro.DocumentUploadedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.documentId)) {
        this.documentId = data().deepCopy(fields()[0].schema(), other.documentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.applicantId)) {
        this.applicantId = data().deepCopy(fields()[1].schema(), other.applicantId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.loanId)) {
        this.loanId = data().deepCopy(fields()[2].schema(), other.loanId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.documentType)) {
        this.documentType = data().deepCopy(fields()[3].schema(), other.documentType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.filename)) {
        this.filename = data().deepCopy(fields()[4].schema(), other.filename);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.s3Key)) {
        this.s3Key = data().deepCopy(fields()[5].schema(), other.s3Key);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.contentType)) {
        this.contentType = data().deepCopy(fields()[6].schema(), other.contentType);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.fileSize)) {
        this.fileSize = data().deepCopy(fields()[7].schema(), other.fileSize);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.uploadedAt)) {
        this.uploadedAt = data().deepCopy(fields()[8].schema(), other.uploadedAt);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'documentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getDocumentId() {
      return documentId;
    }


    /**
      * Sets the value of the 'documentId' field.
      * @param value The value of 'documentId'.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder setDocumentId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.documentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'documentId' field has been set.
      * @return True if the 'documentId' field has been set, false otherwise.
      */
    public boolean hasDocumentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'documentId' field.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder clearDocumentId() {
      documentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'applicantId' field.
      * @return The value.
      */
    public long getApplicantId() {
      return applicantId;
    }


    /**
      * Sets the value of the 'applicantId' field.
      * @param value The value of 'applicantId'.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder setApplicantId(long value) {
      validate(fields()[1], value);
      this.applicantId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'applicantId' field has been set.
      * @return True if the 'applicantId' field has been set, false otherwise.
      */
    public boolean hasApplicantId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'applicantId' field.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder clearApplicantId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'loanId' field.
      * @return The value.
      */
    public long getLoanId() {
      return loanId;
    }


    /**
      * Sets the value of the 'loanId' field.
      * @param value The value of 'loanId'.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder setLoanId(long value) {
      validate(fields()[2], value);
      this.loanId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'loanId' field has been set.
      * @return True if the 'loanId' field has been set, false otherwise.
      */
    public boolean hasLoanId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'loanId' field.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder clearLoanId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'documentType' field.
      * @return The value.
      */
    public java.lang.CharSequence getDocumentType() {
      return documentType;
    }


    /**
      * Sets the value of the 'documentType' field.
      * @param value The value of 'documentType'.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder setDocumentType(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.documentType = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'documentType' field has been set.
      * @return True if the 'documentType' field has been set, false otherwise.
      */
    public boolean hasDocumentType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'documentType' field.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder clearDocumentType() {
      documentType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'filename' field.
      * @return The value.
      */
    public java.lang.CharSequence getFilename() {
      return filename;
    }


    /**
      * Sets the value of the 'filename' field.
      * @param value The value of 'filename'.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder setFilename(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.filename = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'filename' field has been set.
      * @return True if the 'filename' field has been set, false otherwise.
      */
    public boolean hasFilename() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'filename' field.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder clearFilename() {
      filename = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 's3Key' field.
      * @return The value.
      */
    public java.lang.CharSequence getS3Key() {
      return s3Key;
    }


    /**
      * Sets the value of the 's3Key' field.
      * @param value The value of 's3Key'.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder setS3Key(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.s3Key = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 's3Key' field has been set.
      * @return True if the 's3Key' field has been set, false otherwise.
      */
    public boolean hasS3Key() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 's3Key' field.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder clearS3Key() {
      s3Key = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'contentType' field.
      * @return The value.
      */
    public java.lang.CharSequence getContentType() {
      return contentType;
    }


    /**
      * Sets the value of the 'contentType' field.
      * @param value The value of 'contentType'.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder setContentType(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.contentType = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'contentType' field has been set.
      * @return True if the 'contentType' field has been set, false otherwise.
      */
    public boolean hasContentType() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'contentType' field.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder clearContentType() {
      contentType = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'fileSize' field.
      * @return The value.
      */
    public long getFileSize() {
      return fileSize;
    }


    /**
      * Sets the value of the 'fileSize' field.
      * @param value The value of 'fileSize'.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder setFileSize(long value) {
      validate(fields()[7], value);
      this.fileSize = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'fileSize' field has been set.
      * @return True if the 'fileSize' field has been set, false otherwise.
      */
    public boolean hasFileSize() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'fileSize' field.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder clearFileSize() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'uploadedAt' field.
      * @return The value.
      */
    public java.lang.CharSequence getUploadedAt() {
      return uploadedAt;
    }


    /**
      * Sets the value of the 'uploadedAt' field.
      * @param value The value of 'uploadedAt'.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder setUploadedAt(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.uploadedAt = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'uploadedAt' field has been set.
      * @return True if the 'uploadedAt' field has been set, false otherwise.
      */
    public boolean hasUploadedAt() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'uploadedAt' field.
      * @return This builder.
      */
    public com.educationloan.avro.DocumentUploadedEvent.Builder clearUploadedAt() {
      uploadedAt = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DocumentUploadedEvent build() {
      try {
        DocumentUploadedEvent record = new DocumentUploadedEvent();
        record.documentId = fieldSetFlags()[0] ? this.documentId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.applicantId = fieldSetFlags()[1] ? this.applicantId : (java.lang.Long) defaultValue(fields()[1]);
        record.loanId = fieldSetFlags()[2] ? this.loanId : (java.lang.Long) defaultValue(fields()[2]);
        record.documentType = fieldSetFlags()[3] ? this.documentType : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.filename = fieldSetFlags()[4] ? this.filename : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.s3Key = fieldSetFlags()[5] ? this.s3Key : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.contentType = fieldSetFlags()[6] ? this.contentType : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.fileSize = fieldSetFlags()[7] ? this.fileSize : (java.lang.Long) defaultValue(fields()[7]);
        record.uploadedAt = fieldSetFlags()[8] ? this.uploadedAt : (java.lang.CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DocumentUploadedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<DocumentUploadedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DocumentUploadedEvent>
    READER$ = (org.apache.avro.io.DatumReader<DocumentUploadedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.documentId);

    out.writeLong(this.applicantId);

    out.writeLong(this.loanId);

    out.writeString(this.documentType);

    out.writeString(this.filename);

    out.writeString(this.s3Key);

    out.writeString(this.contentType);

    out.writeLong(this.fileSize);

    out.writeString(this.uploadedAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.documentId = in.readString(this.documentId instanceof Utf8 ? (Utf8)this.documentId : null);

      this.applicantId = in.readLong();

      this.loanId = in.readLong();

      this.documentType = in.readString(this.documentType instanceof Utf8 ? (Utf8)this.documentType : null);

      this.filename = in.readString(this.filename instanceof Utf8 ? (Utf8)this.filename : null);

      this.s3Key = in.readString(this.s3Key instanceof Utf8 ? (Utf8)this.s3Key : null);

      this.contentType = in.readString(this.contentType instanceof Utf8 ? (Utf8)this.contentType : null);

      this.fileSize = in.readLong();

      this.uploadedAt = in.readString(this.uploadedAt instanceof Utf8 ? (Utf8)this.uploadedAt : null);

    } else {
      for (int i = 0; i < 9; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.documentId = in.readString(this.documentId instanceof Utf8 ? (Utf8)this.documentId : null);
          break;

        case 1:
          this.applicantId = in.readLong();
          break;

        case 2:
          this.loanId = in.readLong();
          break;

        case 3:
          this.documentType = in.readString(this.documentType instanceof Utf8 ? (Utf8)this.documentType : null);
          break;

        case 4:
          this.filename = in.readString(this.filename instanceof Utf8 ? (Utf8)this.filename : null);
          break;

        case 5:
          this.s3Key = in.readString(this.s3Key instanceof Utf8 ? (Utf8)this.s3Key : null);
          break;

        case 6:
          this.contentType = in.readString(this.contentType instanceof Utf8 ? (Utf8)this.contentType : null);
          break;

        case 7:
          this.fileSize = in.readLong();
          break;

        case 8:
          this.uploadedAt = in.readString(this.uploadedAt instanceof Utf8 ? (Utf8)this.uploadedAt : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










